---
- name: Installing zabbix agent rpm package
  shell: "wget http://repo.zabbix.com/zabbix/3.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.0-1+trusty_all.deb"

- name: dpkg packages...
  command: dpkg -i zabbix-release_3.0-1+trusty_all.deb

- name: Update the cache...
  apt:
    update_cache: yes

- name: Installing Zabbix Agent ...
  apt: name=zabbix-agent state=installed

- template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    mode: 0644


- name: Restarting service
  command:  /etc/init.d/zabbix-agent restart 
